/**
 * This class is generated by jOOQ
 */
package com.si.btp.module.tiers.data.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Adresse implements Serializable {

    private static final long serialVersionUID = -1836988087;

    private Integer   id;
    private String    codeAdresse;
    private String    adresse;
    private String    cp;
    private String    ville;
    private String    telephone;
    private String    mobile;
    private String    fax;
    private String    email;
    private LocalDate dateOfCreate;
    private LocalDate dateOfUpdate;

    public Adresse() {}

    public Adresse(Adresse value) {
        this.id = value.id;
        this.codeAdresse = value.codeAdresse;
        this.adresse = value.adresse;
        this.cp = value.cp;
        this.ville = value.ville;
        this.telephone = value.telephone;
        this.mobile = value.mobile;
        this.fax = value.fax;
        this.email = value.email;
        this.dateOfCreate = value.dateOfCreate;
        this.dateOfUpdate = value.dateOfUpdate;
    }

    public Adresse(
        Integer   id,
        String    codeAdresse,
        String    adresse,
        String    cp,
        String    ville,
        String    telephone,
        String    mobile,
        String    fax,
        String    email,
        LocalDate dateOfCreate,
        LocalDate dateOfUpdate
    ) {
        this.id = id;
        this.codeAdresse = codeAdresse;
        this.adresse = adresse;
        this.cp = cp;
        this.ville = ville;
        this.telephone = telephone;
        this.mobile = mobile;
        this.fax = fax;
        this.email = email;
        this.dateOfCreate = dateOfCreate;
        this.dateOfUpdate = dateOfUpdate;
    }

    public Integer getId() {
        return this.id;
    }

    public Adresse setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getCodeAdresse() {
        return this.codeAdresse;
    }

    public Adresse setCodeAdresse(String codeAdresse) {
        this.codeAdresse = codeAdresse;
        return this;
    }

    public String getAdresse() {
        return this.adresse;
    }

    public Adresse setAdresse(String adresse) {
        this.adresse = adresse;
        return this;
    }

    public String getCp() {
        return this.cp;
    }

    public Adresse setCp(String cp) {
        this.cp = cp;
        return this;
    }

    public String getVille() {
        return this.ville;
    }

    public Adresse setVille(String ville) {
        this.ville = ville;
        return this;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public Adresse setTelephone(String telephone) {
        this.telephone = telephone;
        return this;
    }

    public String getMobile() {
        return this.mobile;
    }

    public Adresse setMobile(String mobile) {
        this.mobile = mobile;
        return this;
    }

    public String getFax() {
        return this.fax;
    }

    public Adresse setFax(String fax) {
        this.fax = fax;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public Adresse setEmail(String email) {
        this.email = email;
        return this;
    }

    public LocalDate getDateOfCreate() {
        return this.dateOfCreate;
    }

    public Adresse setDateOfCreate(LocalDate dateOfCreate) {
        this.dateOfCreate = dateOfCreate;
        return this;
    }

    public LocalDate getDateOfUpdate() {
        return this.dateOfUpdate;
    }

    public Adresse setDateOfUpdate(LocalDate dateOfUpdate) {
        this.dateOfUpdate = dateOfUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Adresse (");

        sb.append(id);
        sb.append(", ").append(codeAdresse);
        sb.append(", ").append(adresse);
        sb.append(", ").append(cp);
        sb.append(", ").append(ville);
        sb.append(", ").append(telephone);
        sb.append(", ").append(mobile);
        sb.append(", ").append(fax);
        sb.append(", ").append(email);
        sb.append(", ").append(dateOfCreate);
        sb.append(", ").append(dateOfUpdate);

        sb.append(")");
        return sb.toString();
    }
}
