/**
 * This class is generated by jOOQ
 */
package com.si.btp.module.tiers.data.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categorie implements Serializable {

    private static final long serialVersionUID = -1195694101;

    private Integer   id;
    private String    abreviation;
    private String    designation;
    private Boolean   visibleouinon;
    private LocalDate dateOfCreate;
    private LocalDate dateOfUpdate;

    public Categorie() {}

    public Categorie(Categorie value) {
        this.id = value.id;
        this.abreviation = value.abreviation;
        this.designation = value.designation;
        this.visibleouinon = value.visibleouinon;
        this.dateOfCreate = value.dateOfCreate;
        this.dateOfUpdate = value.dateOfUpdate;
    }

    public Categorie(
        Integer   id,
        String    abreviation,
        String    designation,
        Boolean   visibleouinon,
        LocalDate dateOfCreate,
        LocalDate dateOfUpdate
    ) {
        this.id = id;
        this.abreviation = abreviation;
        this.designation = designation;
        this.visibleouinon = visibleouinon;
        this.dateOfCreate = dateOfCreate;
        this.dateOfUpdate = dateOfUpdate;
    }

    public Integer getId() {
        return this.id;
    }

    public Categorie setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getAbreviation() {
        return this.abreviation;
    }

    public Categorie setAbreviation(String abreviation) {
        this.abreviation = abreviation;
        return this;
    }

    public String getDesignation() {
        return this.designation;
    }

    public Categorie setDesignation(String designation) {
        this.designation = designation;
        return this;
    }

    public Boolean getVisibleouinon() {
        return this.visibleouinon;
    }

    public Categorie setVisibleouinon(Boolean visibleouinon) {
        this.visibleouinon = visibleouinon;
        return this;
    }

    public LocalDate getDateOfCreate() {
        return this.dateOfCreate;
    }

    public Categorie setDateOfCreate(LocalDate dateOfCreate) {
        this.dateOfCreate = dateOfCreate;
        return this;
    }

    public LocalDate getDateOfUpdate() {
        return this.dateOfUpdate;
    }

    public Categorie setDateOfUpdate(LocalDate dateOfUpdate) {
        this.dateOfUpdate = dateOfUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Categorie (");

        sb.append(id);
        sb.append(", ").append(abreviation);
        sb.append(", ").append(designation);
        sb.append(", ").append(visibleouinon);
        sb.append(", ").append(dateOfCreate);
        sb.append(", ").append(dateOfUpdate);

        sb.append(")");
        return sb.toString();
    }
}
