/**
 * This class is generated by jOOQ
 */
package com.si.btp.module.tiers.data.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contact implements Serializable {

    private static final long serialVersionUID = -1954955295;

    private Integer   id;
    private String    nom;
    private String    prenom;
    private String    telephone;
    private String    mobile;
    private String    fax;
    private String    email;
    private LocalDate dateOfCreate;
    private LocalDate dateOfUpdate;

    public Contact() {}

    public Contact(Contact value) {
        this.id = value.id;
        this.nom = value.nom;
        this.prenom = value.prenom;
        this.telephone = value.telephone;
        this.mobile = value.mobile;
        this.fax = value.fax;
        this.email = value.email;
        this.dateOfCreate = value.dateOfCreate;
        this.dateOfUpdate = value.dateOfUpdate;
    }

    public Contact(
        Integer   id,
        String    nom,
        String    prenom,
        String    telephone,
        String    mobile,
        String    fax,
        String    email,
        LocalDate dateOfCreate,
        LocalDate dateOfUpdate
    ) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        this.telephone = telephone;
        this.mobile = mobile;
        this.fax = fax;
        this.email = email;
        this.dateOfCreate = dateOfCreate;
        this.dateOfUpdate = dateOfUpdate;
    }

    public Integer getId() {
        return this.id;
    }

    public Contact setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getNom() {
        return this.nom;
    }

    public Contact setNom(String nom) {
        this.nom = nom;
        return this;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public Contact setPrenom(String prenom) {
        this.prenom = prenom;
        return this;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public Contact setTelephone(String telephone) {
        this.telephone = telephone;
        return this;
    }

    public String getMobile() {
        return this.mobile;
    }

    public Contact setMobile(String mobile) {
        this.mobile = mobile;
        return this;
    }

    public String getFax() {
        return this.fax;
    }

    public Contact setFax(String fax) {
        this.fax = fax;
        return this;
    }

    public String getEmail() {
        return this.email;
    }

    public Contact setEmail(String email) {
        this.email = email;
        return this;
    }

    public LocalDate getDateOfCreate() {
        return this.dateOfCreate;
    }

    public Contact setDateOfCreate(LocalDate dateOfCreate) {
        this.dateOfCreate = dateOfCreate;
        return this;
    }

    public LocalDate getDateOfUpdate() {
        return this.dateOfUpdate;
    }

    public Contact setDateOfUpdate(LocalDate dateOfUpdate) {
        this.dateOfUpdate = dateOfUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Contact (");

        sb.append(id);
        sb.append(", ").append(nom);
        sb.append(", ").append(prenom);
        sb.append(", ").append(telephone);
        sb.append(", ").append(mobile);
        sb.append(", ").append(fax);
        sb.append(", ").append(email);
        sb.append(", ").append(dateOfCreate);
        sb.append(", ").append(dateOfUpdate);

        sb.append(")");
        return sb.toString();
    }
}
