/**
 * This class is generated by jOOQ
 */
package com.si.btp.module.tiers.data.domain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entreprise implements Serializable {

    private static final long serialVersionUID = 409514324;

    private Integer   id;
    private String    code;
    private String    commentaire;
    private String    statut;
    private String    nom;
    private String    enseigne;
    private String    siren;
    private Integer   categorieId;
    private Integer   adresseId;
    private Integer   contactId;
    private LocalDate dateOfCreate;
    private LocalDate dateOfUpdate;

    public Entreprise() {}

    public Entreprise(Entreprise value) {
        this.id = value.id;
        this.code = value.code;
        this.commentaire = value.commentaire;
        this.statut = value.statut;
        this.nom = value.nom;
        this.enseigne = value.enseigne;
        this.siren = value.siren;
        this.categorieId = value.categorieId;
        this.adresseId = value.adresseId;
        this.contactId = value.contactId;
        this.dateOfCreate = value.dateOfCreate;
        this.dateOfUpdate = value.dateOfUpdate;
    }

    public Entreprise(
        Integer   id,
        String    code,
        String    commentaire,
        String    statut,
        String    nom,
        String    enseigne,
        String    siren,
        Integer   categorieId,
        Integer   adresseId,
        Integer   contactId,
        LocalDate dateOfCreate,
        LocalDate dateOfUpdate
    ) {
        this.id = id;
        this.code = code;
        this.commentaire = commentaire;
        this.statut = statut;
        this.nom = nom;
        this.enseigne = enseigne;
        this.siren = siren;
        this.categorieId = categorieId;
        this.adresseId = adresseId;
        this.contactId = contactId;
        this.dateOfCreate = dateOfCreate;
        this.dateOfUpdate = dateOfUpdate;
    }

    public Integer getId() {
        return this.id;
    }

    public Entreprise setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getCode() {
        return this.code;
    }

    public Entreprise setCode(String code) {
        this.code = code;
        return this;
    }

    public String getCommentaire() {
        return this.commentaire;
    }

    public Entreprise setCommentaire(String commentaire) {
        this.commentaire = commentaire;
        return this;
    }

    public String getStatut() {
        return this.statut;
    }

    public Entreprise setStatut(String statut) {
        this.statut = statut;
        return this;
    }

    public String getNom() {
        return this.nom;
    }

    public Entreprise setNom(String nom) {
        this.nom = nom;
        return this;
    }

    public String getEnseigne() {
        return this.enseigne;
    }

    public Entreprise setEnseigne(String enseigne) {
        this.enseigne = enseigne;
        return this;
    }

    public String getSiren() {
        return this.siren;
    }

    public Entreprise setSiren(String siren) {
        this.siren = siren;
        return this;
    }

    public Integer getCategorieId() {
        return this.categorieId;
    }

    public Entreprise setCategorieId(Integer categorieId) {
        this.categorieId = categorieId;
        return this;
    }

    public Integer getAdresseId() {
        return this.adresseId;
    }

    public Entreprise setAdresseId(Integer adresseId) {
        this.adresseId = adresseId;
        return this;
    }

    public Integer getContactId() {
        return this.contactId;
    }

    public Entreprise setContactId(Integer contactId) {
        this.contactId = contactId;
        return this;
    }

    public LocalDate getDateOfCreate() {
        return this.dateOfCreate;
    }

    public Entreprise setDateOfCreate(LocalDate dateOfCreate) {
        this.dateOfCreate = dateOfCreate;
        return this;
    }

    public LocalDate getDateOfUpdate() {
        return this.dateOfUpdate;
    }

    public Entreprise setDateOfUpdate(LocalDate dateOfUpdate) {
        this.dateOfUpdate = dateOfUpdate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Entreprise (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(commentaire);
        sb.append(", ").append(statut);
        sb.append(", ").append(nom);
        sb.append(", ").append(enseigne);
        sb.append(", ").append(siren);
        sb.append(", ").append(categorieId);
        sb.append(", ").append(adresseId);
        sb.append(", ").append(contactId);
        sb.append(", ").append(dateOfCreate);
        sb.append(", ").append(dateOfUpdate);

        sb.append(")");
        return sb.toString();
    }
}
