/**
 * This class is generated by jOOQ
 */
package com.si.btp.module.tiers.data.domain.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Particulier implements Serializable {

    private static final long serialVersionUID = 78103657;

    private Integer id;
    private String  code;
    private String  commentaire;
    private String  civilite;
    private String  nom;
    private String  prenom;
    private Integer categorieId;
    private Integer adresseId;
    private Integer contactId;
    private Date    createDate;
    private Date    updateDate;

    public Particulier() {}

    public Particulier(Particulier value) {
        this.id = value.id;
        this.code = value.code;
        this.commentaire = value.commentaire;
        this.civilite = value.civilite;
        this.nom = value.nom;
        this.prenom = value.prenom;
        this.categorieId = value.categorieId;
        this.adresseId = value.adresseId;
        this.contactId = value.contactId;
        this.createDate = value.createDate;
        this.updateDate = value.updateDate;
    }

    public Particulier(
        Integer id,
        String  code,
        String  commentaire,
        String  civilite,
        String  nom,
        String  prenom,
        Integer categorieId,
        Integer adresseId,
        Integer contactId,
        Date    createDate,
        Date    updateDate
    ) {
        this.id = id;
        this.code = code;
        this.commentaire = commentaire;
        this.civilite = civilite;
        this.nom = nom;
        this.prenom = prenom;
        this.categorieId = categorieId;
        this.adresseId = adresseId;
        this.contactId = contactId;
        this.createDate = createDate;
        this.updateDate = updateDate;
    }

    public Integer getId() {
        return this.id;
    }

    public Particulier setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getCode() {
        return this.code;
    }

    public Particulier setCode(String code) {
        this.code = code;
        return this;
    }

    public String getCommentaire() {
        return this.commentaire;
    }

    public Particulier setCommentaire(String commentaire) {
        this.commentaire = commentaire;
        return this;
    }

    public String getCivilite() {
        return this.civilite;
    }

    public Particulier setCivilite(String civilite) {
        this.civilite = civilite;
        return this;
    }

    public String getNom() {
        return this.nom;
    }

    public Particulier setNom(String nom) {
        this.nom = nom;
        return this;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public Particulier setPrenom(String prenom) {
        this.prenom = prenom;
        return this;
    }

    public Integer getCategorieId() {
        return this.categorieId;
    }

    public Particulier setCategorieId(Integer categorieId) {
        this.categorieId = categorieId;
        return this;
    }

    public Integer getAdresseId() {
        return this.adresseId;
    }

    public Particulier setAdresseId(Integer adresseId) {
        this.adresseId = adresseId;
        return this;
    }

    public Integer getContactId() {
        return this.contactId;
    }

    public Particulier setContactId(Integer contactId) {
        this.contactId = contactId;
        return this;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public Particulier setCreateDate(Date createDate) {
        this.createDate = createDate;
        return this;
    }

    public Date getUpdateDate() {
        return this.updateDate;
    }

    public Particulier setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Particulier (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(commentaire);
        sb.append(", ").append(civilite);
        sb.append(", ").append(nom);
        sb.append(", ").append(prenom);
        sb.append(", ").append(categorieId);
        sb.append(", ").append(adresseId);
        sb.append(", ").append(contactId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updateDate);

        sb.append(")");
        return sb.toString();
    }
}
