/**
 * This class is generated by jOOQ
 */
package com.si.btp.module.tiers.data.domain.tables;


import com.si.btp.module.tiers.data.converter.LocalDateConverter;
import com.si.btp.module.tiers.data.domain.Keys;
import com.si.btp.module.tiers.data.domain.Public;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Categorie extends TableImpl<Record> {

    private static final long serialVersionUID = -1815875327;

    /**
     * The reference instance of <code>PUBLIC.CATEGORIE</code>
     */
    public static final Categorie CATEGORIE = new Categorie();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>PUBLIC.CATEGORIE.ID</code>.
     */
    public final TableField<Record, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CATEGORIE.ABREVIATION</code>.
     */
    public final TableField<Record, String> ABREVIATION = createField("ABREVIATION", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>PUBLIC.CATEGORIE.DESIGNATION</code>.
     */
    public final TableField<Record, String> DESIGNATION = createField("DESIGNATION", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>PUBLIC.CATEGORIE.VISIBLEOUINON</code>.
     */
    public final TableField<Record, Boolean> VISIBLEOUINON = createField("VISIBLEOUINON", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>PUBLIC.CATEGORIE.DATE_OF_CREATE</code>.
     */
    public final TableField<Record, LocalDate> DATE_OF_CREATE = createField("DATE_OF_CREATE", org.jooq.impl.SQLDataType.DATE.defaultValue(org.jooq.impl.DSL.field("CURRENT_DATE()", org.jooq.impl.SQLDataType.DATE)), this, "", new LocalDateConverter());

    /**
     * The column <code>PUBLIC.CATEGORIE.DATE_OF_UPDATE</code>.
     */
    public final TableField<Record, LocalDate> DATE_OF_UPDATE = createField("DATE_OF_UPDATE", org.jooq.impl.SQLDataType.DATE, this, "", new LocalDateConverter());

    /**
     * Create a <code>PUBLIC.CATEGORIE</code> table reference
     */
    public Categorie() {
        this("CATEGORIE", null);
    }

    /**
     * Create an aliased <code>PUBLIC.CATEGORIE</code> table reference
     */
    public Categorie(String alias) {
        this(alias, CATEGORIE);
    }

    private Categorie(String alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Categorie(String alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.PK_CATEGORIE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.PK_CATEGORIE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Categorie as(String alias) {
        return new Categorie(alias, this);
    }

    /**
     * Rename this table
     */
    public Categorie rename(String name) {
        return new Categorie(name, null);
    }
}
