/**
 * This class is generated by jOOQ
 */
package com.si.btp.module.tiers.data.domain;


import com.si.btp.module.tiers.data.domain.tables.Adresse;
import com.si.btp.module.tiers.data.domain.tables.Categorie;
import com.si.btp.module.tiers.data.domain.tables.Contact;
import com.si.btp.module.tiers.data.domain.tables.Entreprise;
import com.si.btp.module.tiers.data.domain.tables.Particulier;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> PK_CONTACT_ID = UniqueKeys0.PK_CONTACT_ID;
    public static final UniqueKey<Record> PK_ADRESSE_ID = UniqueKeys0.PK_ADRESSE_ID;
    public static final UniqueKey<Record> PK_CATEGORIE_ID = UniqueKeys0.PK_CATEGORIE_ID;
    public static final UniqueKey<Record> PK_ENTREPRISE_ID = UniqueKeys0.PK_ENTREPRISE_ID;
    public static final UniqueKey<Record> UNQ_ENTRPRISE_CODE = UniqueKeys0.UNQ_ENTRPRISE_CODE;
    public static final UniqueKey<Record> PK_PARTICULIER_ID = UniqueKeys0.PK_PARTICULIER_ID;
    public static final UniqueKey<Record> UNQ_PARTICULIER_CODE = UniqueKeys0.UNQ_PARTICULIER_CODE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<Record, Record> FK_ENTREPRISE_CATEGORIE = ForeignKeys0.FK_ENTREPRISE_CATEGORIE;
    public static final ForeignKey<Record, Record> FK_ENTREPRISE_ADRESSE = ForeignKeys0.FK_ENTREPRISE_ADRESSE;
    public static final ForeignKey<Record, Record> FK_ENTREPRISE_CONTACT = ForeignKeys0.FK_ENTREPRISE_CONTACT;
    public static final ForeignKey<Record, Record> FK_PARTICULIER_CATEGORIE = ForeignKeys0.FK_PARTICULIER_CATEGORIE;
    public static final ForeignKey<Record, Record> FK_PARTICULIER_ADRESSE = ForeignKeys0.FK_PARTICULIER_ADRESSE;
    public static final ForeignKey<Record, Record> FK_PARTICULIER_CONTACT = ForeignKeys0.FK_PARTICULIER_CONTACT;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<Record> PK_CONTACT_ID = createUniqueKey(Contact.CONTACT, "PK_CONTACT_ID", Contact.CONTACT.ID);
        public static final UniqueKey<Record> PK_ADRESSE_ID = createUniqueKey(Adresse.ADRESSE, "PK_ADRESSE_ID", Adresse.ADRESSE.ID);
        public static final UniqueKey<Record> PK_CATEGORIE_ID = createUniqueKey(Categorie.CATEGORIE, "PK_CATEGORIE_ID", Categorie.CATEGORIE.ID);
        public static final UniqueKey<Record> PK_ENTREPRISE_ID = createUniqueKey(Entreprise.ENTREPRISE, "PK_ENTREPRISE_ID", Entreprise.ENTREPRISE.ID);
        public static final UniqueKey<Record> UNQ_ENTRPRISE_CODE = createUniqueKey(Entreprise.ENTREPRISE, "UNQ_ENTRPRISE_CODE", Entreprise.ENTREPRISE.CODE);
        public static final UniqueKey<Record> PK_PARTICULIER_ID = createUniqueKey(Particulier.PARTICULIER, "PK_PARTICULIER_ID", Particulier.PARTICULIER.ID);
        public static final UniqueKey<Record> UNQ_PARTICULIER_CODE = createUniqueKey(Particulier.PARTICULIER, "UNQ_PARTICULIER_CODE", Particulier.PARTICULIER.CODE);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<Record, Record> FK_ENTREPRISE_CATEGORIE = createForeignKey(com.si.btp.module.tiers.data.domain.Keys.PK_CATEGORIE_ID, Entreprise.ENTREPRISE, "FK_ENTREPRISE_CATEGORIE", Entreprise.ENTREPRISE.CATEGORIE_ID);
        public static final ForeignKey<Record, Record> FK_ENTREPRISE_ADRESSE = createForeignKey(com.si.btp.module.tiers.data.domain.Keys.PK_ADRESSE_ID, Entreprise.ENTREPRISE, "FK_ENTREPRISE_ADRESSE", Entreprise.ENTREPRISE.ADRESSE_ID);
        public static final ForeignKey<Record, Record> FK_ENTREPRISE_CONTACT = createForeignKey(com.si.btp.module.tiers.data.domain.Keys.PK_CONTACT_ID, Entreprise.ENTREPRISE, "FK_ENTREPRISE_CONTACT", Entreprise.ENTREPRISE.CONTACT_ID);
        public static final ForeignKey<Record, Record> FK_PARTICULIER_CATEGORIE = createForeignKey(com.si.btp.module.tiers.data.domain.Keys.PK_CATEGORIE_ID, Particulier.PARTICULIER, "FK_PARTICULIER_CATEGORIE", Particulier.PARTICULIER.CATEGORIE_ID);
        public static final ForeignKey<Record, Record> FK_PARTICULIER_ADRESSE = createForeignKey(com.si.btp.module.tiers.data.domain.Keys.PK_ADRESSE_ID, Particulier.PARTICULIER, "FK_PARTICULIER_ADRESSE", Particulier.PARTICULIER.ADRESSE_ID);
        public static final ForeignKey<Record, Record> FK_PARTICULIER_CONTACT = createForeignKey(com.si.btp.module.tiers.data.domain.Keys.PK_CONTACT_ID, Particulier.PARTICULIER, "FK_PARTICULIER_CONTACT", Particulier.PARTICULIER.CONTACT_ID);
    }
}
