/**
 * This class is generated by jOOQ
 */
package com.si.btp.module.tiers.data.domain;


import com.si.btp.module.tiers.data.domain.tables.Adresse;
import com.si.btp.module.tiers.data.domain.tables.Categorie;
import com.si.btp.module.tiers.data.domain.tables.Contact;
import com.si.btp.module.tiers.data.domain.tables.Entreprise;
import com.si.btp.module.tiers.data.domain.tables.Particulier;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 553827033;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.CONTACT</code>.
     */
    public final Contact CONTACT = com.si.btp.module.tiers.data.domain.tables.Contact.CONTACT;

    /**
     * The table <code>PUBLIC.ADRESSE</code>.
     */
    public final Adresse ADRESSE = com.si.btp.module.tiers.data.domain.tables.Adresse.ADRESSE;

    /**
     * The table <code>PUBLIC.CATEGORIE</code>.
     */
    public final Categorie CATEGORIE = com.si.btp.module.tiers.data.domain.tables.Categorie.CATEGORIE;

    /**
     * The table <code>PUBLIC.ENTREPRISE</code>.
     */
    public final Entreprise ENTREPRISE = com.si.btp.module.tiers.data.domain.tables.Entreprise.ENTREPRISE;

    /**
     * The table <code>PUBLIC.PARTICULIER</code>.
     */
    public final Particulier PARTICULIER = com.si.btp.module.tiers.data.domain.tables.Particulier.PARTICULIER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Contact.CONTACT,
            Adresse.ADRESSE,
            Categorie.CATEGORIE,
            Entreprise.ENTREPRISE,
            Particulier.PARTICULIER);
    }
}
