/**
 * This class is generated by jOOQ
 */
package com.si.btp.module.tiers.data.domain;


import com.si.btp.module.tiers.data.domain.tables.Adresse;
import com.si.btp.module.tiers.data.domain.tables.Categorie;
import com.si.btp.module.tiers.data.domain.tables.Contact;
import com.si.btp.module.tiers.data.domain.tables.Entreprise;
import com.si.btp.module.tiers.data.domain.tables.Particulier;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CONTACT</code>.
     */
    public static final Contact CONTACT = com.si.btp.module.tiers.data.domain.tables.Contact.CONTACT;

    /**
     * The table <code>PUBLIC.ADRESSE</code>.
     */
    public static final Adresse ADRESSE = com.si.btp.module.tiers.data.domain.tables.Adresse.ADRESSE;

    /**
     * The table <code>PUBLIC.CATEGORIE</code>.
     */
    public static final Categorie CATEGORIE = com.si.btp.module.tiers.data.domain.tables.Categorie.CATEGORIE;

    /**
     * The table <code>PUBLIC.ENTREPRISE</code>.
     */
    public static final Entreprise ENTREPRISE = com.si.btp.module.tiers.data.domain.tables.Entreprise.ENTREPRISE;

    /**
     * The table <code>PUBLIC.PARTICULIER</code>.
     */
    public static final Particulier PARTICULIER = com.si.btp.module.tiers.data.domain.tables.Particulier.PARTICULIER;
}
